ethereum/solc-js

downloadCurrentVersion.js

The current code breaks on versions such as 2.5.10.

Supporting versions with 2-digit numbers

---

README.md
test/package.js
wrapper.js

This is only the internal part of the linker, which replaces library references with addresses in a given bytecode. Code taken form browser-solidity. First step to implement #4.
The higher level method will need to support JSON input and perhaps handle multiple versions of the same library name.

Import basic bytecode linking code from browser-solidity

---

README.md
package.json
solcjs
test/cli.js
test/index.js

Moving the compiler part of my old tool https://github.com/axic/ethereumjs-codesim.
Would it make sense mirroring the CLI of `solc` or should we diverge?
Note: we cannot 100% mirror as many features are lacking (as of today) in soljson.
It is very basic at the moment, only supports `--bin`. Most of the features (AST, ABI, interface) can be supported.

Introduce cli - solcjs

---

README.md

Includes an alternative installation process because the version on npm hasn't been updated yet so it doesn't include `solcjs`.

Minor corrections to documentation

---

package.json
test/determinism.js
test/package.js

Having to write `result.contracts['file:contract'].bytecode` instead of `result.contracts.contract.bytecode` is pretty annoying and it does not help making it two-stage because you usually have a `.` in the filename.

Update to version 0.4.9.

---

README.md
package.json
test/package.js
translate.js
wrapper.js

Depends on #93. Deprecates #33.
Todo:

Implement JSON I/O wrapper for older compilers

---

solcjs

On Windows systems, the ':' (colon) character is reserved and invalid in file names. This patch adds the --replace-colon option that replaces the colon with '-' (minus) in output file names.
Should fix #109

Replace ':' (and `.` `/`) with '-' in output filenames for solcjs

---

README.md
wrapper.js

There aren't any local binaries or a bin folder for that matter so removing a method that tries to access them. I've removed `useVersion` and updated the README to reflect that.
I was getting this error when trying to simply import the solc package:
```
./~/solc/wrapper.js
Module not found: Can't resolve './bin' in '/node_modules/solc'
```
Ref issue #143

Remove `useVersion`, no local binaries in bin 

---

package.json

I was received this error since execute `npm install` from Command Prompt:
```
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solc@0.4.21 prepublish: `./downloadCurrentVersion.js && ./verifyVersion.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the solc@0.4.21 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chiro\AppData\Roaming\npm-cache\_logs\2018-03-23T10_31_11_253Z-debug.log
```
**Reason:**  `'.' is not recognized as an internal or external command,`

Fix installation's error on Windows

---

linker.js
test/package.js

When using standard JSON i/o, input parameter `libraries` to function `linkBytecode` is of form
```
{
"myFile.sol": {
"MyLib": "0x123123..."
}
}
```
I believe the typeof check is meant to be applied to the value not the the key of `libraryName`

Fix linkBytecode to work properly with two-level lists

---

README.md
test/package.js
wrapper.js

Part of #120.
This a 0.5.0 breaking change.

Remove solc.linkBytecode because the preferred one is linker.linkBytecode

---

test/package.js

Part of  https://github.com/ethereum/solidity/pull/5145. Part of #120.

Use bytecode for the linker tests

---

linker.js
package.json
test/linker.js

Required by https://github.com/ethereum/solidity/pull/5145

Support linking via hash.

---

solcjs

Use standard json internally in solcjs in every case

---

test/cli.js
test/determinism.js
test/package.js
wrapper.js

Implements #120 and https://github.com/ethereum/solidity/issues/3452
This is the hard-breaking option, while #122 implements a more incremental change, but carries a lot more baggage.
Depends on #256. Needs test changes.

New breaking api, compile() is an alias to compileStandardWrapper()

---

wrapper.js

This is a more consistent way to see if a certain feature supported, than using `supportsXYZ`.
In preparation for #120.

Add solc.features.* listing

---

test/package.js

Reorder standard JSON tests to prefer the 'wrapper' as the non-lowlevel API)

---

test/package.js
wrapper.js

Use solc.features.* instead of solc.supports* in tests

---

.travis.yml
solcjs
test/cli.js

Fix --standard-json on solcjs

---

package.json
smtchecker.js
solcjs

and rerun compiler with given responses

Run SMT solver on requested queries

---

translate.js

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace:
> str.replace(regexp|substr, newSubstr|function)
> The replace() method returns a new string with some or all matches of a pattern replaced by a replacement. The pattern can be a string or a RegExp, and the replacement can be a string or a function to be called for each match. If pattern is a string, only the first occurrence will be replaced.
The original code had an unused argument and it always replaced the first match only.

Fix translate.escapeString to actually replace all occurrances

---

README.md

Answer this https://github.com/ethereum/solc-js/issues/31#issuecomment-445249699
Closes #31.

Add readme for browser version

---

package.json

A new tape version was released two days ago which makes our test setup fail. I'm still not sure whether it is a bug with our tests or with tape, but this should get us through the release tomorrow.
I'm suspecting [this PR](https://github.com/substack/tape/pull/403) being the cause of it.

Force tape version to 4.9.2.

---

solcjs

fix: ensure CLI replaces path separator on Windows platforms correctly

---

downloadCurrentVersion.js
linker.js
package.json

Replaces both with `js-sha3`.  `ethereumjs-util` and `keccak` NPM packages both have native bindings in their dependency tree which means they depend on node-gyp along the way.  `js-sha3` on the other hand is a JavaScript-native implementation of the sha3 family of hashing functions, which relieves a number of `node-gyp` and native binding related issues.
Fixes #356

Removes ethereumjs-util and keccak dependencies.

---

package.json

This is the complementary test PR to https://github.com/ethereum/solidity/pull/7199.
Fixes https://github.com/ethereum/solidity/issues/5963. Closes https://github.com/ethereum/solidity/pull/7199

Require tape ^4.11.0 instead of fixing tape 4.9.2.

---

test/DAO/DAO.sol
test/DAO050/DAO.sol
test/DAO050/ManagedAccount.sol
test/DAO050/Token.sol
test/DAO050/TokenCreation.sol
test/cli.js
test/determinism.js

Needed for https://github.com/ethereum/solidity/pull/7350.
This PR updates the workaround for breaking releases used by `npm test`. It also updates the newly added 0.6.0 tests to pass with `array.length` being an rvalue now.

[0.6.0] Set up tests and fix read-only array length

---

package.json
solcjs
test/cli.js

Works towards resolving #361.  Yargs brings in ~26 packages while commander brings in 1.

Replaces yargs with commander.

---

package.json

For whatever reason, most of the packages used in scripts do not properly package cross-platform scripts (only exception is `tape`).  This change makes it so the scripts are run from node_modules rather than as commands.

Updates scripts so that they run on Windows.

---

smtchecker.js
smtsolver.js
test/index.js
test/smtCheckerTests/smoke.sol
test/smtcallback.js
wrapper.js

Depends on #410
New version of https://github.com/ethereum/solc-js/pull/316
Depends on https://github.com/ethereum/solidity/pull/7447
With this change, one can call
`compileStandard(..., smtchecker.smtCallback(smtsolver.smtSolver), ...)`
and get the SMTChecker working only requiring a local `z3` or `cvc4`.

Add callback kind to solc

---

linker.js
test/compiler.js
translate.js

Increase code coverage for older compiler versions

---

test/compiler.js

This makes the tests to work with all releases (so far).

Support errors returned by 0.4.12

---

downloadCurrentVersion.js
wrapper.js

Fixes #445.
- Rate limit is being hit causing flakey builds for anyone who depends on solc-js remote downloading in their software. The change to GitHub raw URLs avoids hitting rate limits.
- ~~Ability to override the repository all together with an environment variable `SOLC_REPO`. Allowing people to use alternative repos, including internal.~~

Use GitHub raw.githubusercontent.com to avoid rate limiting

---

wrapper.js

This should be backwards compatible just as it is, shouldn't it? Let's see what the tests say.
Relates to https://github.com/ethereum/solidity/pull/9111

Pass the wasm signature to addFunction.

---

downloadCurrentVersion.js
test/compiler.js
wrapper.js

Currently `solc-js` is not using [solc-bin.ethereum.org](https://solc-bin.ethereum.org) domain to get `soljson.js` binaries from `solc-bin` repository. Instead it fetches the files from [raw.githubusercontent.com](https://raw.githubusercontent.com) URLs. This prevents us from freely reorganizing the structure of `solc-bin` since, unlike Github Pages, it does not provide the original file content when you access it via a symlink. Instead you get a text file with a path and `sojc-js` can't handle that currently (https://github.com/ethereum/solc-bin/pull/43, https://github.com/ethereum/solc-bin/pull/44).
Not using a domain under our control is also an obstacle to transparently moving files to a different hosting and this is exactly what we're facing now (see …

Getting soljson.js via dedicated solc-bin.ethereum.org domain

---

downloadCurrentVersion.js
package.json
wrapper.js

Requested in https://github.com/ethereum/solc-js/pull/479#discussion_r457598976
This PR adds a dependency on [follow-redirects](https://github.com/follow-redirects/follow-redirects) which has no dependencies of its own and consists of a single `.js` file (not counting the `http.js`/`https.js`/`debug.js` stubs). It has a few dev dependencies but we're already using most of them (`node_modules/` gets just 100 kB bigger after installing them on my machine).
It doesn't really do all that much (most of its code is stuff we don't need right now: callback handling, configuration options, HTTP methods other than `GET`) so it wouldn't be hard to write from scratch but I think it's already small enough.

Following HTTP redirects

---

test/smtcallback.js

In https://github.com/ethereum/solidity/pull/9352, CHC reports assertion failures without considering the callback results, since there is no CHC portfolio the same way there is an SMTPortfolio. So we either need this PR or a mechanism that allows us to choose the engine, where we could choose BMC only and not have the extra if here.

From 0.7.0 on CHC reports assertion failures ingoring the callback

---

test/smtcallback.js

This is needed for the cases where z3 is nondeterministic (unfortunately)

Fix test expectation

---

test/compiler.js

We can do this differently, but we should really have something like this. It's extremely annoying for running the tests from the solidity repo, that you can't force it to only run against the version of ``soljson.js`` you want...

Add test option to disable remote version tests.

---

solcjs

Fixes #527.
Related to https://github.com/ethereum/solidity/issues/11521.
Currently the default value of the flag is indefined so `enabled` key gets stripped from the optimizer settings dict and we and up with `OptimiserSettings::none()` rather than `OptimiserSettings::minimal()`.

Use minimal optimizer settings in solcjs when --optimize flag is missing

---

.circleci/config.yml
package.json

Leftover in https://github.com/ethereum/solidity/pull/11750 and my guess what currently breaks the solidity tests.

Remove `npm run prepublishOnly` from `pretest`.

---

package.json
solcjs

Extracted from #544 because it looks useful for #546 as well.
- Newer versions of the library allow having parameters that take multiple values, which is needed in #544.
- Apparently the `InvalidArgumentError` is only available in never versions (https://github.com/ethereum/solc-js/pull/546#discussion_r705200874).

Upgrade `commander` dependency to the latest version

---

.circleci/config.yml

These are the current stable releases: https://nodejs.org/en/about/releases/

CircleCI: Run tests on Node 14 and Node 16

---

solcjs
test/cli.js

Adding parameter to specify the optimizer runs options. Example use: 
`node ./solcjs --optimize-runs 666 --bin test/resources/fixtureSmoke.sol`
Resolves https://github.com/ethereum/solidity/issues/11857

Adding parameter to solcjs for the optimizer run option

---

solcjs

Somewhat related to https://github.com/ethereum/solidity/issues/11583.
This PR adds two options
- `--pretty-print` - we already have that in solc and soon it will work for Standard jSON too (https://github.com/ethereum/solidity/pull/11639).
- `--verbose` - prints extra info, most importantly the Standard JSON input to the compiler. It's most useful when not using `--standard-json` option because then it's the script that constructs the input JSON. I wanted to see it pretty much every time I was solving a problem with solc-js and I always ended up hacking it in with debug prints. Having this as an option would make working with solc-js much more convenient for me and I think it might be useful for others too.

[solcjs] `--pretty-json` and `--verbose` options

---

README.md
solcjs
test/cli.js
test/resources/importCallback/base/contractA.sol
test/resources/importCallback/base/contractB.sol
test/resources/importCallback/contractC.sol
test/resources/importCallback/includeA/libX.sol
test/resources/importCallback/includeA/libY.sol
test/resources/importCallback/includeA/utils.sol
test/resources/importCallback/includeB/libZ.sol

Implements the `solc-js` part of https://github.com/ethereum/solidity/pull/11848.
Depends on #547.
The implementation is simplified compared to `solc` and argument processing from the `commander` works a bit differently than in `boost::program_options`:
- There's no check against path conflicts (two files specified on the CLI getting the same source unit name after base path/include path stripping).
- There's no check against ambiguous imports (one import matching multiple files in base path/include paths).
- `commander` allows specifying multiple paths while using the option only once `--include-path path1/ path2/ path3/`. This is a bit inconvenient because if it's the last option, it consumes the names of the input files. E.g. `solcjs --base-path base/ --include-paths node_modules/ …

[solcjs] `--include-path` option

---

.circleci/config.yml

Nodejs v17 is out now and people will probably want to use it. I know that some frameworks do not support it yet (Hardhat does not, not sure about Truffle) but solc-js does seem to work so would not hurt to have a CI run for it, at least until v18 is released.
Also, not sure why coveralls is still on v12 but seems to work fine with v16. Not sure if it's worth putting it on v17 already though.

CI run for nodejs v17

---

package.json
wrapper.js

Fixes #576.
`require-from-string` is a tiny package and we're even not using all of its features. It's also no longer maintained because https://github.com/floatdrop/require-from-string/issues/18 is has not been fixed since 2018. This PR replaces it with a few lines of code and drops the dependency.
The real question is how do we test this properly? It passes our current tests but the problem exists only on Webpack.
Also, the author or the PR that broke Webpack compatibility claims that Webpack does not even provide `module` (https://github.com/floatdrop/require-from-string/pull/6#issuecomment-369216332). Not sure how to verify that.

Drop require-from-string to restore Webpack compatibility

---

smtsolver.ts

Looks like `tmp` is not being imported incorrectly. Not sure how that passed tests in #566 but tests are failing due to this in the main repo (https://github.com/ethereum/solidity/pull/12583).
```
TypeError: Cannot read property 'fileSync' of undefined
```
In addition to merging this, we should really investigate why it passed our CI.
```
git clone https://github.com/ethereum/solc-js/
cd solc-js/
npm install
npm run updateBinary
npm run test
```
```
ok 1108 should be truthy
/tmp/v0.1.1+commit.6ff4cd6.js:84
throw ex;
^
TypeError: Cannot read property 'fileSync' of undefined
at solve (/tmp/d/solc-js/dist/smtsolver.js:36:35)
at Object.handleSMTQueries (/tmp/d/solc-js/dist/smtchecker.js:19:28)
at Test.<anonymous> (/tmp/d/solc-js/dist/test/smtchecker.js:78:47)
at Test.bound [as _cb] …
```

Fix the import of `tmp` in `smtsolver.ts`

---

index.ts
solc.ts
test/compiler.ts
test/smtcallback.ts
test/smtchecker.ts
verifyVersion.ts

By exporting under the root, javascript importing modules will continue
to use it as expected without first having to index `.default.`

fix: export all properties under the root instead of default

---

abi.ts
downloadCurrentVersion.ts
index.ts
linker.ts
smtchecker.ts
smtsolver.ts
solc.ts
test/abi.ts
test/cli.ts
test/compiler.ts
test/linker.ts
test/smtcallback.ts
test/smtchecker.ts
test/translate.ts
translate.ts
tsconfig.json
verifyVersion.ts
wrapper.ts

By doing so allows the commonjs default imports to work as expected not blocking
backwards compatibility.
reference: https://www.typescriptlang.org/tsconfig#esModuleInterop
This will stop imports like the following from being a issue.
```js
const wrapper = require('solc/wrapper).default;
```
they will now work as expected as
```js
const wrapper = require('solc/wrapper);
```

fix: use esModuleInterop to resolve commonjs default require

---

package.json
test/compiler.ts

Fix: Ensure that tests work even if /tmp is not accessible

---

abi.ts
build/pack-publish-block.js
downloadCurrentVersion.ts
index.ts
linker.ts
package.json
smtchecker.ts
smtsolver.ts
solc.ts
test/abi.ts
test/cli.ts
test/compiler.ts
test/linker.ts
test/smtcallback.ts
test/smtchecker.ts
test/translate.ts
translate.ts
tsconfig.json
verifyVersion.ts
wrapper.ts

~Depends on #595. Should not be merged before that PR.~ Merged.
When releasing the package, and users begin to use the application, the following is a example import which can take place.
```js
const wrapper = require('solc/wrapper');
```
With the introduction of the typescript support, the content is built into the dist folder. Resulting in the build folder to look like the following.
```
package.json
dist/wrapper.js
dist/solc.js
```
The following change ensures that we publish the dist folder directly which will result in a flatten published folder like the following 
```
package.json
wrapper.js
solc.js
```
which will allow the code example to function correctly without changing the import path to `solc/dist/wrapper`. This change will go in hand with the following PR #595 to allow the …

fix: use npm run publish to release the dist folder directly

---

.circleci/config.yml

~Depends on #596. Should not be merged before that PR.~ Merged.
This PR adds CI jobs that run latest Truffle and Hardhat with injected solc-js. This runs their test suites and also tries to compile a sample project.

CI tests based on Truffle and Hardhat

---

common/interfaces.ts
wrapper.ts

This will resolve any linting concerns that would block this from passing the linting requirements. Additionally, this upgrades vars to let and const where applicable for maintainability. 
When performing binary support checks, always return a function that is callable from the consumer. This can just error for example in the below implementation. Reducing the need for complicated backward compatibility requirements when future changes occur. 
```js
if (!('_solidity_lsp_start' in soljson)) {
return () => {
throw new Error('lsp is not supported on this version.');
};
}
```
`wrapper.js` has a plan refactor to simplify maintainability and remove some of the complicated nested function calls. This change will be included in that so I did not make any additional changes outside of the current …

LSP Integration: simple refactor to resolve linting and legacy variables

---

.circleci/config.yml

Workaround for https://github.com/NomicFoundation/hardhat/issues/2486.

Add `yarn build` to `hardhat-core-default-solc` job to work around broken parallel tests

---

common/types.ts
linker.ts

This change provides some basic type support for the internal and exported methods within `linker.ts`, includes support documentation where missing for the consumer. The target result of this `PR` is to increase readability, maintainability and start the introduction of types.
This is the continuous development happening on top of #566 to improve user consumption, and development experience. 
Depends on #603 and #594 
This is currently rebased on #603 so just validate the latest commit.

Provide type support to linker.ts 

---

package.json

Fixes #622.
I guess this is enough to fix the issue, but maybe better if @cameel and/or @stephensli confirmed.

Add the missing `common/helpers.ts` to `package.json`

---

.circleci/config.yml

~Depends on #623.~ Merged.
This PR changes the mechanism for injecting solc-js as a dependency of Truffle and Hardhat, introduced in #594, to make it more robust.
Normally when you install a boilerplate project you get multiple copies of `solc` in the dependency tree and looks like the method I used did not actually replace all of them. The way it was done is generally very hacky - going to the dependency dir and using npm or yarn to install a new version of the dependency. It works most of the time but sometimes also changes the dependency tree in weird ways and, honestly, I don't 100% understand what npm/yarn is exactly doing. Their dependency trees are just too complex.
Now I switched to the `overrides` feature, newly added in npm 8.3. This should be more reliable. yarn has a similar …

Fix solc-js injection in CI

---

.circleci/config.yml

Extracted from #594. ~It duplicates one commit from that PR to avoid having to depend on it.~ Rebased.
~Depends on https://github.com/ethereum/solidity/pull/12594.~ Merged.
This PR adds a test run using the `solc-js.sh` script from the main repo. PRs in solc-js sometimes break the main repo but we don't detect that until after we merge them because that test runs only on the `master` branch. This check is meant to act as a canary to detect such breakage already in PRs.

Run solc-js test from main repo in CI

---

test/cli.ts

Currently tests in `cli.ts` are hard-coded to require a binary with version matching `package.json`. This not true in general and causes problems in #598.
This PR changes the test to only require the output from `--version` to match the output of `version()` function in the binary. I also kept a modified version of the previous check as a sanity check - to match that the output actually looks like our version string.

Fix CLI `--version` test to use version from the binary not `package.json`

---

.circleci/config.yml

It used to require 12 and would file with a newer one. Apparently now it requires 14 or later.

Run Truffle on newer node.js in CI

---

.circleci/config.yml

Related to https://github.com/ethereum/solidity/pull/13068 and the [feeback we received in CircleCI's config review](https://gist.github.com/jenny-miggin/9578d2e52b383b3787e265c80e5f6b03).
Since the `circleci/` images are no longer updated there's no version 18 so this is needed if we want to use any newer versions.

Switch away from deprecated `circleci/node` images and update node.js in CI to 18

---

package.json

Fixes #635.
Closes #647.
Adding the LICENSE and README.md files back to tarball.
Output from the `npm run build:tarball` command:

Adding command to copy meta files into dist dir

---

bindings/compile.ts
bindings/core.ts
bindings/helpers.ts
bindings/index.ts
formatters.ts
package.json
wrapper.ts

This change works on refactoring out the wrapper.ts file to allow improved maintainability, extensibility with support of easy typing. The current implementation is one continuous function call which allocates all the bindings with hard to follow scoping.
Any bindings of methods have been split out into the `binding` directly, currently containing the core (anything not compiler related) and compiler related bound functions.
Since the wrapper is the main entry point for most consumers of the service, this should allow cleanly defined types to be exported with the package. Allowing language servers and IDEs to consume the types and expose them to the user for an improved experience. 
* The callback implementation to apply changes based on some additional input arguments can now be tackled …

Refactor wrapper.ts to improve maintainability

---

.circleci/config.yml

This PR adds a CI job to perform coding style checks as suggested here: https://github.com/ethereum/solc-js/pull/659#discussion_r978652925
It performs the `eslint` checks for `.js` and `.ts` files using the npm lint script and checks the `.sh` files using the [shellcheck circleCI orb](https://circleci.com/developer/orbs/orb/circleci/shellcheck).

Add CI job to check coding style

---

.github/workflows/scorecards.yml

Closes #661 
As mentioned at #661, I've enabled the [Scorecard GitHub Action](https://github.com/ossf/scorecard-action) with the minimum features and permissions needed. The other ones I've commented to be easier for you to enable it in the future.
Any questions or concerns please feel free to reach me out.

Enable the OpenSSF Scorecard Github Action

---

package.json

Note that CI won't pass until 0.8.23 binaries are published to solc-bin.

Set version to 0.8.23

---

.circleci/config.yml

This bumps all minor versions to latest, and also adds a new run on `node:current` (which is node 21).
It also bumps node version in Hardhat jobs that were not on `current` only because at the time of node 17 Hardhat did not work with it.
Truffle does not work with node 21, but is fine with node 20, which is the current `lts`.

Bump node versions in CI

---

.circleci/config.yml

The long-term solution for problems like #715.
This PR extracts the building of the .tgz package into a separate CI job that's now a dependency of other jobs that use that package. It also adjusts those jobs to rely only on the package and not reach into the checked out repo (that used to be available them).
The package is now a CI artifact and we can use it in our release process instead of building it locally, which is error prone.

Building release package in CI

---

package.json

Note that CI won't pass until 0.8.24 binaries are published to solc-bin.

Set version to 0.8.24

---

.circleci/config.yml

Hardhat builds now depends on rust to be installed. So we need to update the docker images similarly to what we did for solidity: https://github.com/ethereum/solidity/commit/e7312a501086e1b0751bc3abbc7e7f08de8b8acd

Update hardhat docker images

---

.circleci/config.yml

Since the project was discontinued and it will probably not have support for Cancun hardfork, we are removing it: https://app.circleci.com/pipelines/github/ethereum/solc-js/1456/workflows/1abf0a1a-7667-4cd3-be03-ded214c7839a/jobs/8582

Remove truffle suite from CI

---

package.json

Note that this won't pass until the new 0.8.25 binaries are pushed to solc-bin

Set version to 0.8.25

---

.circleci/config.yml

We should really have a nightly run in this repo because there's not that much traffic here and we sometimes miss CI being broken. With a nightly run we won't have to remember to run CI manually and we'll actually notice breakage as it happens, not just before a release.
It would be useful to also have notifications for the Matrix CI channel. And a run with a nightly binary from solc-bin, which would have detected breakage like #732 and, combined with that notification, would let us know when nightlies in solc-bin are broken (https://github.com/ethereum/solidity/issues/13507). I did not do any of those things though. This is just a simple nightly workflow build quickly out of what I already had at hand.

Add a nightly CI run

---

README.md

Fix a typo in the "Browser Usage" section in the README

---

test/compiler.ts

The test is trying to parse `{invalid`. Doing so with `nlohmann::json` will create the following error:
```json
{
"errors": [
{
"component": "general",
"formattedMessage": "[json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing object key - invalid literal; last read: '{i'; expected string literal",
"message": "[json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing object key - invalid literal; last read: '{i'; expected string literal",
"severity": "error",
"type": "JSONError"
}
]
}
```
This PR updates the expected error message.

Update test "compiling standard JSON (invalid JSON)" to be nlohmann::json compatible

---

.circleci/config.yml

Workaround for https://app.circleci.com/pipelines/github/ethereum/solc-js/1540/workflows/d9c4642f-a94e-4aa1-a8e4-90904d689a69/jobs/9433?invite=true#step-113-530140_122. I still need to identify the root cause of the issue (maybe hardhat heuristics?) and report upstream if necessary.
I also imported the `GITHUB_ACCESS_TOKEN` of Solidity CircleCI config to solc-js.

Use hardhat latest releases instead of main branch

---

package.json

NOTE: build will not pass until binaries are pushed to solc-bin

Set version to 0.8.26

---

README.md
smtsolver.ts

Depends on https://github.com/ethereum/solidity/pull/15078

Update cvc4 to cvc5

---

package.json

NOTE: build will not pass until binaries are pushed to solc-bin

Set version to 0.8.27

---

.circleci/config.yml

During the 0.8.27 release I noticed that we missed to upgrade the image used by `solidity-solcjs-ext-test` in our CI config.
This PR upgrades such CircleCI convenience image to fix the following warning: https://app.circleci.com/pipelines/github/ethereum/solc-js/1670/workflows/34f69e77-0e63-491e-8d41-d0c62663c700/jobs/10461
More info about the deprecation here: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

Use cimg/node instead of deprecated circleci/node

---

.circleci/config.yml

As discussed in https://github.com/ethereum/solc-js/issues/752, this removes two Hardhat-related jobs that are not necessary and that will stop working soon when we remove those tests from the Hardhat repo.

Remove unnecessary Hardhat-related CI jobs

---

.circleci/config.yml
package.json

This PR removes Node.js 10 from our CI as it started failing due to many dependencies increasing their Node.js version requirements. See: https://app.circleci.com/pipelines/github/ethereum/solc-js/1775/workflows/14eb5b72-7624-47e5-a302-a407c1fd4f58/jobs/11376/parallel-runs/0?invite=true#step-105-0_136 and this error: https://app.circleci.com/pipelines/github/ethereum/solc-js/1775/workflows/14eb5b72-7624-47e5-a302-a407c1fd4f58/jobs/11376?invite=true#step-108-209_118, which is because `Object.fromEntries` is only available in Node.js 12+. We could potentially workaround the issue using `DISABLE_V8_COMPILE_CACHE=1`, but I believe that it makes more sense to update the packages.
Also, ESLint v8 dropped support for Node.js 10, as noted here …

Drop nodejs 10

---

package.json
tsconfig.json

- add .d.ts files to final build with `declaration: true` in tsconfig 
- include .d.ts file in final tarball

feat: Add typings to npm package

---

.github/workflows/scorecards.yml

Update `actions/upload-artifact: v3` to `v4` as in https://github.com/ethereum/solidity-website/pull/127 and bump scorecards actions.
The PR also fixes: https://github.com/ethereum/solc-js/actions/runs/13807880368/job/38622476340. See related issue: https://github.com/ossf/scorecard-action/issues/1498

Bump versions of scorecards action
