ethereum/solc-js

- README.md
- index.js
This was such an annoying bug with such a simple resolution. For more details see #6.
> Fix the file import callback

- README.md
Fixes chriseth/browser-solidity#113
> Add section about Electron

- README.md
@Denton-L feel free to cherry-pick this and make changes to it
> Include link to solidity and solc-bin in the README

- index.js
Not sure how to name these two. Any ideas?
(Is needed to accomplish the end goal of https://github.com/ethereum/browser-solidity/pull/54)
> Add two flags for the supported features (supportsMulti and supportsImportCallback)

- solcjs
- test/cli.js
connects to https://github.com/ethereum/solc-js/issues/38
not sure about this place 
https://github.com/ethereum/solc-js/pull/40/files#diff-3858b4a7a818753cc90f630536cbf94dR70
> remove 'interface'

- wrapper.js
Aims to fix https://github.com/ethereum/browser-solidity/issues/212
> Catch & rethrow exception so the function pointer can be freed

- package.json
- solcjs
Fixes #51 
Create output folder if it does not exist
> Always create output directory

- .travis.yml
- wrapper.js
This also disables node 0.10 to 0.12 from Travis testing.
> Node.js fixes for version 4 to 7

- solcjs
This (hopefully) will fix #84 and also be a little less rude to anyone who is using this library by putting things back the way they were before the script ran.
Fixes #34 and #84.
> Attempts to fix exception handlers added by emscripten.

- package.json
- verifyVersion.js
> Verify version matches in prepublish

- README.md
> Mention that solcjs is incompatible with solc

- solcjs
- test/cli.js
> Report warnings/errors on CLI

- solcjs
> Support JSON I/O in CLI

- README.md
> Cleanup code style in readme

- solcjs
> Raise error message if writing a file failed

- abi.js
- test/abi.js
> Add stateMutability field to ABI translator

- .gitignore
- .travis.yml
- package.json
- wrapper.js
+ Lint check as part of `npm test`
+ Add the generated files to .gitignore
See the commit log for more detail.
> Tweaks package.json and .gitignore

- package.json
Fixes #150 and https://github.com/ethereum/browser-solidity/issues/847.
> Include linker.js in package.json for npm

- solcjs
- test/DAO/DAO.sol
- test/DAO/ManagedAccount.sol
- test/DAO/Token.sol
- test/DAO/TokenCreation.sol
- test/cli.js
Fixes #104.
Credits to @chevdor for this.
> Use stderr for errors in solcjs

- test/abi.js
> Properly test fallback functions in abi translator

- .gitignore
- test/package.js
> Add solcjs output to .gitignore

- test/package.js
> Add comprehensive tests for the file import callback

- README.md
> Document compileStandardWrapper

- test/package.js
- wrapper.js
>  Raise error if invalid import callback is supplied

- test/DAO/DAO.sol
- test/DAO/Token.sol
- test/DAO/TokenCreation.sol
- test/DAO040/DAO.sol
- test/DAO040/ManagedAccount.sol
- test/DAO040/Token.sol
- test/DAO040/TokenCreation.sol
- test/cli.js
- test/determinism.js
I created a fork, since I don't have write permissions for the repository.
So far this is entirely untested.
> Update DAO contracts.

- test/DAO/DAO.sol
- test/DAO/TokenCreation.sol
Some of these were missed in 40151cc. Fixes #222.
> Update DAO contracts (use strict address literals)

- test/DAO/DAO.sol
- test/DAO/ManagedAccount.sol
- test/DAO/TokenCreation.sol
Required for ethereum/solidity#4215
> Updates DAO contracts to new constructor syntax

- test/DAO/DAO.sol
> Update DAO contracts (use emit for events)

- test/DAO/DAO.sol
- test/DAO/ManagedAccount.sol
Required for https://github.com/ethereum/solidity/pull/4376
> Make fallback functions external.

- test/DAO/DAO.sol
- test/DAO/Token.sol
- test/DAO/TokenCreation.sol
- test/DAO040/DAO.sol
- test/DAO040/Token.sol
- test/DAO040/TokenCreation.sol
Added data locations for function parameters and function return parameters to comply with Solidity v0.5 making default data locations for parameters an error. (https://github.com/ethereum/solidity/pull/4014)
All tests are passing locally.
> Added data locations for function parameters and return parameters.

- test/DAO/DAO.sol
Dependency of https://github.com/ethereum/solidity/pull/4478.
> Add missing storage locations.

- test/DAO/DAO.sol
- test/DAO/TokenCreation.sol
Dependency of https://github.com/ethereum/solidity/pull/4439.
> Cast contracts to address before accessing address members.

- test/package.js
Required by https://github.com/ethereum/solidity/pull/4430
> Adds visibility specifier

- test/DAO/DAO.sol
Needed for https://github.com/ethereum/solidity/pull/4740.
> Replace empty return statements in functions that have return values.

- test/DAO/DAO.sol
- test/DAO/ManagedAccount.sol
- test/DAO/Token.sol
- test/DAO/TokenCreation.sol
Fixes the solc-js tests for https://github.com/ethereum/solidity/pull/4590
> Remove extra guard for non-payable functions that use msg.value

- test/DAO/DAO.sol
- test/DAO/ManagedAccount.sol
- test/DAO/TokenCreation.sol
Needed in https://github.com/ethereum/solidity/pull/4829
> Adjust (new) syntax for bare calls

- wrapper.js
Part of https://github.com/ethereum/solidity/issues/3452
> Support the new solc public methods (solidity_compile/solidity_version/solidity_license)

- test/DAO/DAO.sol
- test/DAO/ManagedAccount.sol
- test/DAO/TokenCreation.sol
Needed for ethereum/solidity#4911. Should be safe to merge, since ethereum/solidity#4926 is already merged now.
> Change ``address`` to ``address payable`` where needed.

- .circleci/config.yml
> Move CI To Circleci

- wrapper.js
Part of #120 and https://github.com/ethereum/solidity/issues/3452
> Refactor wrapper (and make compileJSON optional)

- wrapper.js
> Add safeguard(s) in compileStandardWrapper for some edge cases

- .circleci/config.yml
> Change circleci config so that coveralls is only run on Node 10

- wrapper.js
> Support compileJSON missing in compile

- test/package.js
- wrapper.js
> Support running tests even if compileJSON is missing

- test/determinism.js
> Move determinism test to use compileStandardWrapper

- test/cli.js
- test/determinism.js
- test/package.js
- wrapper.js
This reverts commit 7d6f480d29ed50539db8b2b8606822fb529a00a6, reversing
changes made to 80a50f9c069dfcf2520b65f0169c66bebadaab8d.
(Reverts the merge #259 as it was merged prematurely.)
> Revert "Merge pull request #259 from ethereum/new-breaking-api"

- test/package.js
> Use compileStandardWrapper in loadRemoteVersion test

- .travis.yml
- test/index.js
> Do not run CLI tests on Node 4

- README.md
> Clarify loadRemoteVersion example 

- test/index.js
- test/smtchecker.js
Part of #307.
This also ensures that code coverage includes `smtchecker.js`
> Add SMTChecker smoke tests

- translate.js
> Fix translate.escapeString to actually replace all occurrances

- smtsolver.js
> Remove dependency on fs-extra in smtsolver

- package.json
> Update to latest yargs

- test/cli.js
- test/contracts/Smoke.sol
> Use smoke test with CLI

- README.md
- test/package.js
- wrapper.js
> Backport new callback API to 0.5

- test/compiler.js
- wrapper.js
> Backport new callback API to 0.5 to compileStandardWrapper

- test/compiler.js
- wrapper.js
Findings:
- 0.4.26 works
- 0.3.6 works
- 0.2.1 works
- 0.2.0 works
- 0.1.6 works
- 0.1.1 works
Closes #96.
> Run tests with multiple solc versions

- wrapper.js
> Reorder functions in wrapper (move version/license early)

- test/compiler.js
- wrapper.js
Part of #406. 
Depends on #408.
> Change lowlevel API to also expect a callback object

- test/compiler.js
- translate.js
- wrapper.js
> Small test improvements

- test/compiler.js
> Add tests for gas estimation

- test/compiler.js
> Workaround 0.3.x non-determinism bug (this test has been removed in 0.6.x anyway)

- test/compiler.js
> Test translator for 0.4.0 and 0.4.11 as well

- smtsolver.js
Hopefully this will fix the solc-js CI problems in the Solidity tests
> Use the same z3 options as Solidity does

- abi.js
- test/abi.js
Fixes #500.
@yann300 can you try this?
> Do not translate constant functions from <0.4.0 as payable

- test/smtcallback.js
Needed by https://github.com/ethereum/solidity/pull/10477
> Prepare SMT comparison for counterexamples

- wrapper.js
> Use correct url for binaries.

- test/smtCheckerTests/smoke_with_engine.sol
- test/smtCheckerTests/smoke_with_multi_engine.sol
- test/smtcallback.js
And prepare for smtchecker pragma removal
> Use SMT engine

- README.md
- downloadCurrentVersion.js
- test/compiler.js
> Use binaries.soliditylang.org link consistently

- common/helpers.ts
- linker.ts
The target result of this `PR` is to increase readability, maintainability and support the start the introduction of types.
This is the continuous development happening on top of #566 to improve user consumption, and development experience. 
Depends on #594
> Refactor of linker.ts 

- smtchecker.ts
- solc.ts
Hello,
This tiny PR will fix : 
- 1 typo in `smtchecker.ts`
- 1 typo in `solc.ts`
Bye! :robot:
> docs: fix typos

- README.md
This PR adds a note in the README about the need for the use of web workers when using `solc` in web browsers as suggested by https://github.com/ethereum/solc-js/issues/581 .
> Add web worker example in README

- .circleci/config.yml
Fix the same issue of https://github.com/ethereum/solidity/pull/15035#issue-2246547812.
> Fix pnpm broken lockfile
